### ISSUE TITLE
Java Server Compile Errors

### ISSUE THREAD

**Issue by flasheryu** [TheBlueMatt/RelayNode#10]
Hi,Matt.

I am confronted with the following errors when compiling the java relay server:

RelayConnection.java:368: error: cannot find symbol
			if (msgLength > Block.MAX_BLOCK_SIZE)
			                     ^
  symbol:   variable MAX_BLOCK_SIZE
  location: class Block
RelayConnection.java:517: error: cannot find symbol
		return Block.MAX_BLOCK_SIZE; // Its bigger than 64k, so buffers will just be 64k in size
		            ^
  symbol:   variable MAX_BLOCK_SIZE
  location: class Block
RelayConnectionListener.java:43: error: no suitable constructor found for Peer(NetworkParameters,VersionMessage,<null>,PeerAddress)
				final Peer emulatedPeer = new Peer(params, fakeVersionMessage, null, new PeerAddress(inetAddress));
				                          ^
    constructor Peer.Peer(NetworkParameters,BlockChain,String,String) is not applicable
      (actual argument VersionMessage cannot be converted to BlockChain by method invocation conversion)
    constructor Peer.Peer(NetworkParameters,BlockChain,VersionMessage) is not applicable
      (actual and formal argument lists differ in length)

So my question is which version of bitcoinj are you using in this project?

BTW, i tried branch master and release-0.9 using the official code here: https://code.google.com/p/bitcoinj/source/browse/
and also tried the bitcoinj in your repository, but neither of them works.

Thanks for your help!

**Comment by TheBlueMatt** [comment]
The java server's performance was never that great and it is no longer supported. You should use the c++ one instead.

**Comment by TheBlueMatt** [comment]
I removed the Java client instead.
