### ISSUE TITLE
Relaynode no longer identifies its User Agent and gets disconnected.

### ISSUE THREAD

**Issue by jedimstr** [TheBlueMatt/RelayNode#20]
I just pulled the Oct 20th commits including: 9b326ec071dd03be74d2496f251b6ac76596ab1d
After making the new C++ client node and starting it, all seems fine from the client, but my -nowallet bitcoin node used for mining on p2pool sees an issue.  The relay client connects without a User Agent and NA ping time, and then after a minute or so disconnects totally (no longer on peer list).  The node running log shows no issues.  Previous version connected with an identifying User Agent and stayed connected.

**Comment by jedimstr** [comment]
So I had to go back a few commit versions until I found one that worked again.
Apparently the last one that identified the /RelayNetworkClient:42/ as User Agent and stayed connected was commit: ddd0829a1ecf69110a7140ebd23ec982ad8b16cf back in September.

**Comment by p3yot3** [comment]
Hi jedimstr,

Strange, it's working fine on my node with no issues......

**Comment by TheBlueMatt** [comment]
Strange, I cant seem to reproduce...Are you suggesting a51c67e74fe88de51383dfee436646ce4d7a714f broke your connection? It shouldnt be able to effect client stuff at all? Have you tried 5da6c4f9fc305e37003c08dbb0d8b14509385871?

**Comment by jedimstr** [comment]
Yup, pretty much.

Here are screenshots of the behavior.

First with ddd0829a1ecf69110a7140ebd23ec982ad8b16cf

![bitcoin_core_-_node](https://cloud.githubusercontent.com/assets/5072618/10707309/8fa1a780-79be-11e5-9c07-2acdbf7b622d.png)


Then showing my checkout and build of a51c67e74fe88de51383dfee436646ce4d7a714f

![jedimstr_ _screen_0__zsh____jedimstr_cylonbasestar___relaynode_c_____121x77___pts_16_ _ssh_ _ttys001](https://cloud.githubusercontent.com/assets/5072618/10707313/ad7aa69e-79be-11e5-9606-7f506e6be680.png)


Then on startup this empty UserAgent for same IP shows:

![bitcoin_core_-_node 2](https://cloud.githubusercontent.com/assets/5072618/10707319/c217f214-79be-11e5-9f92-7894ea8bcb42.png)


And then after about a minute or so, it disappears from Bitcoin Core's list:

![bitcoin_core_-_node 3](https://cloud.githubusercontent.com/assets/5072618/10707325/d53d53fc-79be-11e5-876b-618fa2652364.png)

But the running log keeps on going as if it's still connected:

![jedimstr_ _screen_0____relaynetworkclient____jedimstr_cylonbasestar___relaynode_c_____121x77___pts_16_ _ssh_ _ttys001](https://cloud.githubusercontent.com/assets/5072618/10707331/ef3a322a-79be-11e5-8eb0-f5261c833876.png)


The RelayNodeClient is running on Ubuntu and the Bitcoin Core node version v0.11.1 is running on a Mac.

Every version committed after ddd0829a1ecf69110a7140ebd23ec982ad8b16cf is broken like this, and I've tried every one including 5da6c4f9fc305e37003c08dbb0d8b14509385871 with no success.

**Comment by TheBlueMatt** [comment]
I really dont see how that could be...a51c67e74fe88de51383dfee436646ce4d7a714f added only about three LOC that should be NOPs for clients (it was mostly a server commit). Still, I pushed some other stuff I had been testing, so try current master?

**Comment by jedimstr** [comment]
Whatever you added in your new commits fixed it.
Pulled and checked out master (back to HEAD which is 78274d9846cb1e505218bcc9e65fc440dabcb9c1 ) and it's showing the correct UserAgent and staying connected again.  So maybe something was amiss in your previous KeepAlive stuff?

**Comment by TheBlueMatt** [comment]
Strange, closing, then.
