### ISSUE TITLE
Regarding connection port

### ISSUE THREAD

**Issue by jeong760** [TheBlueMatt/RelayNode#29]
Dears,

Which network port should I open on the firewall?

**Comment by TheBlueMatt** [comment]
Clients are all outgoing-TCP, so no inbound ports should need to be opened.

**Comment by jeong760** [comment]
I found that in order to connect an existing relay network I must be open a 8336 port on the firewall.
without open it cannot possible to access on the relay server
 
-----Original Message-----

**Comment by TheBlueMatt** [comment]
Ahh, sorry, yes, I assumed you were asking about inbound ports. Indeed, 8336-tcp-outgoing is required.

**Comment by jeong760** [comment]
No, it is ok. 
but do you know Japan relay network does not working at all. it is not possible to connect on it using its public address. 
 
-----Original Message-----
