### ISSUE TITLE
Python client fails after period with error('unpack str size too short for format',)

### ISSUE THREAD

**Issue by tfgkhj** [TheBlueMatt/RelayNode#3]
('Unknown error processing data from relay node:', error('unpack str size too short for format',))
    ('Lost connect to relay node:', error(61, 'Connection refused'))
    ('Failed to send to relay node: ', error(32, 'Broken pipe'))
    ('Lost connect to bitcoind node:', error(57, 'Socket is not connected'))
    Connected to bitcoind with protocol version 70002
    Finished connect handshake with bitcoind

The client then hangs, connects back to bitcoind but no longer relays any information.

**Comment by TheBlueMatt** [comment]
Please use the C++ client, the python client has now been removed.
